// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;


namespace AssemblyCSharp
{
	public class RX_CardManager
	{
		#region
		private RX_CardManager ()
		{
		}

		private static RX_CardManager s_RX_CardManager = null;

		public static RX_CardManager DefaultManager()
		{
			
			if(s_RX_CardManager == null)
			{
				s_RX_CardManager = new RX_CardManager();
			}
			return s_RX_CardManager;
			
		} 

		#endregion


		/// <summary>
		/// Get A New CardL
		/// </summary>
	
		private List<int> GetNewCardList()
		{
			List<int> cl = new List<int> ();

			for (int i = 0; i < RX_Define.RX_CARD_NUMBER; i++) 
			{
				cl.Add(i);
			}

			return cl;
		}

		public List<RX_Card> Reshuffle()
		{
			//get a new card list
			List<int> the_list = GetNewCardList ();

			//create a shuffle card list
			List<RX_Card> res_list = new List<RX_Card> ();


			Random random = new Random ();
			for (int i = 0; i < RX_Define.RX_CARD_NUMBER; i++) 
			{
				//create a random index within the_list

				int random_index = random.Next(0,the_list.Count);

				//take the random index value into res_list
				res_list.Add(new RX_Card(the_list[random_index]));

				//remove the random index value from the_list
				the_list.RemoveAt(random_index);
			}

			return res_list;
		}


		#region CareSpriteList

		private static List<UISprite> sprite_pool = null;
		private static List<UISprite> Pool{
			get{
				if (sprite_pool == null) {
					sprite_pool = new List<UISprite> ();
				}
				return sprite_pool;
			}
		}
		public static UISprite CreateSpriteBy(RX_Card card,UISprite parent,int x)
		{			
			UISprite sprite = NGUITools.AddChild<UISprite> (parent.gameObject);
			NGUITools.AddWidgetCollider (sprite.gameObject);
			UIButton button = NGUITools.AddMissingComponent<UIButton> (sprite.gameObject);
	
			sprite.depth = x + 300;
			sprite.atlas = RX_Resources.DefaultResources.CardAtlas;
			sprite.spriteName = card.ToString ();
			sprite.SetRect (x, card.PositionY, 42f, 60f);

		
			button.onClick.Add (new EventDelegate (() => {

				card.IsPop = !card.IsPop;
				sprite.SetRect(x,card.PositionY,42f,60f);
				
			}));


			sprite_pool.Add (sprite);

			return sprite;
		}

		public static void RefreshPool()
		{
			for (int i = 0; i < Pool.Count; i++) 
			{
				UnityEngine.GameObject.Destroy (sprite_pool [i].gameObject);
			}
			sprite_pool.RemoveRange (0, sprite_pool.Count);
		}

		#endregion

	}
}

