// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;


namespace AssemblyCSharp
{
	public class RX_CardManager
	{
		#region
		private RX_CardManager ()
		{
		}

		private static RX_CardManager s_RX_CardManager = null;

		public static RX_CardManager DefaultManager()
		{
			
			if(s_RX_CardManager == null)
			{
				s_RX_CardManager = new RX_CardManager();
			}
			return s_RX_CardManager;
			
		} 

		#endregion


		/// <summary>
		/// Get A New CardL
		/// </summary>
	
		private List<int> GetNewCardList()
		{
			List<int> cl = new List<int> ();

			for (int i = 0; i < RX_Define.RX_CARD_NUMBER; i++) 
			{
				cl.Add(i);
			}

			return cl;
		}

		public List<RX_Card> Reshuffle()
		{
			//get a new card list
			List<int> the_list = GetNewCardList ();

			//create a shuffle card list
			List<RX_Card> res_list = new List<RX_Card> ();


			Random random = new Random ();
			for (int i = 0; i < RX_Define.RX_CARD_NUMBER; i++) 
			{
				//create a random index within the_list

				int random_index = random.Next(0,the_list.Count);

				//take the random index value into res_list
				res_list.Add(new RX_Card(the_list[random_index]));

				//remove the random index value from the_list
				the_list.RemoveAt(random_index);
			}

			return res_list;
		}


		#region CareSpriteList

		/// <summary>
		/// 精灵池...
		/// </summary>
		private static List<UISprite> sprite_pool = null;
		private static List<UISprite> Pool{
			get{
				if (sprite_pool == null) {
					sprite_pool = new List<UISprite> ();
				}
				return sprite_pool;
			}
		}

		/// <summary>
		/// 通过一张牌对象和容器对象还有坐标x创建一张图片
		/// </summary>
		/// <returns>The sprite by.</returns>
		/// <param name="card">Card.</param>
		/// <param name="parent">Parent.</param>
		/// <param name="x">The x coordinate.</param>
		public static UISprite CreateSpriteBy(RX_Card card,UISprite parent,int x)
		{			
			//创建精灵对象,通过NGUITools.AddChild函数
			UISprite sprite = NGUITools.AddChild<UISprite> (parent.gameObject);

			//为图片对象添加碰撞器...
			NGUITools.AddWidgetCollider (sprite.gameObject);

			//为一个NGUI的游戏控件,添加缺失的组件
			UIButton button = NGUITools.AddMissingComponent<UIButton> (sprite.gameObject);
	
			sprite.depth = x + 300;
			sprite.atlas = RX_Resources.DefaultResources.CardAtlas;
			sprite.spriteName = card.ToString ();

			//设置NGUI控件在屏幕上的显示位置和大小
			sprite.SetRect (x, card.PositionY, 42f, 60f);

		
			button.onClick.Add (new EventDelegate (() => {

				card.IsPop = !card.IsPop;
				sprite.SetRect(x,card.PositionY,42f,60f);
				
			}));


			//在CreateSpriteBy函数实现的最后
			//将创建的精灵对象添加到sprite池内
			sprite_pool.Add (sprite);

			return sprite;
		}

		/// <summary>
		/// 将数组内的所有游戏对象全部销毁,并且移除数组...
		/// </summary>
		public static void RefreshPool()
		{
			for (int i = 0; i < Pool.Count; i++) 
			{
				//销毁游戏对象
				UnityEngine.GameObject.Destroy (sprite_pool [i].gameObject);
			}
			//从数组内移除所有的游戏对象
			sprite_pool.RemoveRange (0, sprite_pool.Count);
		}

		#endregion

	}
}

