// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace AssemblyCSharp
{
	public class RX_PopCardSetManager
	{
		private static RX_PopCardSetManager s_RX_PopCardSetManager = null;
		private RX_PopCardSetManager ()
		{
		}

		public static RX_PopCardSetManager DefaultManager{
			get{
				if (s_RX_PopCardSetManager == null) {
					s_RX_PopCardSetManager = new RX_PopCardSetManager();
					s_RX_PopCardSetManager.PopList = new List<RX_PopCardSet>();
					s_RX_PopCardSetManager.PopList.Add(new RX_PopCardSet());
				}
				return s_RX_PopCardSetManager;
			}
		}

		private List<RX_PopCardSet> pop_list = null;
		private List<RX_PopCardSet> PopList{
			set{
				pop_list = value;
			}
			get{
				return pop_list;
			}
		}

		private static void AddPop(RX_PopCardSet sender)
		{
			RX_PopCardSetManager.DefaultManager.PopList.Add(sender);
		}

		private static int Count()
		{
			return RX_PopCardSetManager.DefaultManager.PopList.Count;
		}

		private static RX_PopCardSet Last()
		{
			return RX_PopCardSetManager.DefaultManager.PopList[RX_PopCardSetManager.Count() - 1];
		}

		private static bool CompareIn(RX_CardSet sender)
		{
			RX_PopCardSet pop = RX_PopCardSetManager.Last();

			if (pop.ListCardSet.Count == 0) {
				return true;
			}

			if (pop.ListCardSet.Count >= 1) 
			{

				RX_CardSet theCareSet = pop.Last();

				theCareSet = theCareSet.Typer == RX_CARD_SET.RX_TYPE_BUCHU ? pop.Last2(): theCareSet;

				if (theCareSet.Typer == RX_CARD_SET.RX_TYPE_BUCHU && sender.Typer != RX_CARD_SET.RX_TYPE_BUCHU) {
					return true;
				}

				if (sender.Typer == RX_CARD_SET.RX_TYPE_BUCHU) {
					return true;
				}

				if (sender.Typer == RX_CARD_SET.RX_TYPE_WANGZHA)
				{
					return true;
				}

				if (theCareSet.Typer != RX_CARD_SET.RX_TYPE_BOOM && sender.Typer == RX_CARD_SET.RX_TYPE_BOOM) {
					return true;
				}

				if (sender.Typer != theCareSet.Typer) {
					return false;
				}

				if ((int)sender.Level <= (int)theCareSet.Level) {
					return false;
				}
			}

			return true;
		}

		private static void SetNeedCreateCardSet()
		{
			RX_PopCardSet pop = RX_PopCardSetManager.Last();

			if (pop.ListCardSet.Count >= 2) 
			{
				RX_CardSet last_1 = pop.Last();
				RX_CardSet last_2 = pop.Last2();

				if (last_1.Typer == RX_CARD_SET.RX_TYPE_BUCHU && last_2.Typer == RX_CARD_SET.RX_TYPE_BUCHU) 
				{
					RX_PopCardSet pop_cardset = new RX_PopCardSet();
					RX_PopCardSetManager.AddPop(pop_cardset);
				}
			}
		}

		public static string AddCardSet(RX_CardSet sender,out bool isSuccessed)
		{
			if (CompareIn(sender)) 
			{

				RX_PopCardSet pop = RX_PopCardSetManager.Last();

				pop.AddCardSet(sender);

				isSuccessed = true;
				RX_PopCardSetManager.SetNeedCreateCardSet();

				return sender.ToString() + ":success";
			}
			else
			{

				isSuccessed = false;

				return sender.ToString() + ":failed";
			}
		}
	}
}

