// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	/// <summary>
	/// card level
	/// </summary>
	public enum RX_CARD_LEVEL
	{
		RX_LEVEL_3 = 3,
		RX_LEVEL_4 = 4,
		RX_LEVEL_5 = 5,
		RX_LEVEL_6 = 6,
		RX_LEVEL_7 = 7,
		RX_LEVEL_8 = 8,
		RX_LEVEL_9 = 9,
		RX_LEVEL_0 = 10,
		RX_LEVEL_J = 11,
		RX_LEVEL_Q = 12,
		RX_LEVEL_K = 13,
		RX_LEVEL_A = 14,
		RX_LEVEL_2 = 15,
		RX_LEVEL_S = 16,
		RX_LEVEL_B = 17,
	}

	/// <summary>
	/// card name
	/// </summary>
	public enum RX_CARD_NAME
	{
		//hong tao
		RX_NAME_HOT = 0,
		//fang pian
		RX_NAME_FAP = 1,
		//hei tao
		RX_NAME_HET = 2,
		//mei hua
		RX_NAME_MEH = 3,
		//wang
		RX_NAME_KIN = 4,
	}

	/// <summary>
	/// Singleton Define Variables
	/// </summary>
	public class RX_Define
	{
		#region Singleton
		/// <summary>
		/// private constructor
		/// </summary>
		private RX_Define ()
		{
		}

		//Create static variable s_RX_Define
		private static RX_Define s_RX_Define = null;

		//Create static property function DefaultDefine
		public static RX_Define DefaultDefine{
			get{
				if (s_RX_Define == null) {
					s_RX_Define = new RX_Define();
				}
				return s_RX_Define;
			}
		}
		#endregion

		//Create Card Count Variables....
		public const int RX_CARD_NUMBER = 54;

		//
		public const int RX_HOT_NUMBER = 0;

		//
		public const int RX_FAP_NUMBER = 13;

		//
		public const int RX_HET_NUMBER = 26;

		//
		public const int RX_MEH_NUMBER = 39;

		//
		public const int RX_SMA_NUMBER = 52;

		//
		public const int RX_BIG_NUMBER = 53;

		//游戏数据服务器用的url地址
		public const string RX_URI = "http://project.lanou3g.com/game/unity/doudizhu/";

		//游戏房间服务器用到的ip地址
		public const string RX_ServerIP = "115.28.227.1";

		//游戏房间服务器用到的端口
		public const int RX_ServerPort = 23466;
	}
}

