// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class RX_UserManager
	{
		private RX_UserManager()
		{}
		private static RX_UserInfo s_RX_User = null;

		public static RX_UserInfo DefaultUser{
			set{
				s_RX_User = value;
			}
			get{
				return s_RX_User;
			}
		}
	}

	public class RX_UserInfo
	{
		public string user_id{get;set;}
		public string user_name{get;set;}
		public string user_nick{get;set;}
		public string user_score{get;set;}
		public string user_pwd{get;set;}

		public override string ToString ()
		{
			return string.Format ("[RX_UserInfo: user_id={0}, user_name={1}, user_nick={2}, user_score={3}, user_pwd={4}]", user_id, user_name, user_nick, user_score, user_pwd);
		}
	}
}

