// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Xml.Serialization;

namespace AssemblyCSharp
{
	/// <summary>
	/// 用来存储登陆的用户角色,方便在每个场景中获取用户信息
	/// </summary>
	public class RX_UserManager
	{
		private RX_UserManager()
		{}
		private static RX_UserInfo s_RX_User = null;

		public static RX_UserInfo DefaultUser{
			set{
				s_RX_User = value;
			}
			get{
				return s_RX_User;
			}
		}
	}


	/// <summary>
	/// 用户信息实体类
	/// </summary>
	[XmlRoot("rx_user")]
	public class RX_UserInfo
	{
		public string user_id{get;set;}
		public string user_name{get;set;}
		public string user_nick{get;set;}
		public string user_score{get;set;}
		public string user_pwd{get;set;}
		public int seat_index{ get; set;}


		public RX_UserInfo()
		{
		}
		public RX_UserInfo(string name)
		{
			this.user_name = name;
		}

		public override string ToString ()
		{
			return LO_XMLTool.Serializer(typeof(RX_UserInfo),this);
		}

		public bool Equals (RX_UserInfo sender)
		{
			return this.user_id.Equals(sender.user_id);
		}
	}
}

